<a href="https://colab.research.google.com/github/safakatakancelik/portfolio-public/blob/main/notebooks/building_attention_from_scratch/attention_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Implementing Attention

1. Raw attention with word embeddings, no Q/K/V
2. Add Q, K, V matrices
3. Causal masking
4. Softmax
5. Full single-head attention forward pass


6. Rewrite in PyTorch and use a real embedding model
7. Multi-head attention
7. Inspect attention matrices on ambiguous sentences
8. Rewrite as PyTorch nn.Module inside a transformer block (attention → residual → LayerNorm → FFN)

### Learning Goals
- understand raw attention vs learned Q/K/V projections
- see why √d_k scaling prevents softmax saturation
- understand causal masking for autoregressive generation
- read attention maps to see what the model "looks at"
- bridge from numpy prototype to production-style PyTorch code


$$Attention(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$


In [1]:
!pip install torch
!pip install torchtext

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 22.9 MB/s eta 0:00:00


In [2]:
import numpy as np
from scipy.special import softmax

In [3]:
np.random.seed(42)
d_model = 8
d_k = 8

### Step 1: Raw Attention

In [4]:
# building the vocabulary with random vectors
english_words = ["the", "cat", "sat", "on", "the", "mat"]


unique_words = dict.fromkeys(english_words)
vocab = {w: np.random.randn(d_model) for w in unique_words}


X = np.array([vocab[w] for w in english_words])  # (6, 8)


## Attention
attention_scores = X @ X.T / np.sqrt(d_k)  # (6, 8) @ (8, 6) -> (6, 6) attention score for each word pair

print("Tokens:", english_words)
print("\nScores shape:", attention_scores.shape)
print(np.round(attention_scores, 2))

Tokens: ['the', 'cat', 'sat', 'on', 'the', 'mat']

Scores shape: (6, 6)
[[ 2.19 -1.44 -1.61  0.08  2.19 -0.96]
 [-1.44  2.81  1.13  0.38 -1.44  1.98]
 [-1.61  1.13  2.89 -0.85 -1.61  0.37]
 [ 0.08  0.38 -0.85  2.13  0.08  0.03]
 [ 2.19 -1.44 -1.61  0.08  2.19 -0.96]
 [-0.96  1.98  0.37  0.03 -0.96  3.17]]


---


## Step 2: Add Q, K, V matrices

In [5]:
# initialize projection matrices to train
W_q = np.random.randn(d_model, d_k) * 0.01
W_k = np.random.randn(d_model, d_k) * 0.01
W_v = np.random.randn(d_model, d_k) * 0.01


# project embeddings into Q, K, V spaces
Q = X @ W_q
K = X @ W_k
V = X @ W_v

## Attention
attention_scores = Q @ K.T / np.sqrt(d_k)  # (6, 6)

print("Tokens:", english_words)
print("\nScores shape:", attention_scores.shape)
print(np.round(attention_scores, 5))

Tokens: ['the', 'cat', 'sat', 'on', 'the', 'mat']

Scores shape: (6, 6)
[[-5.80e-04  1.02e-03  2.60e-04  2.60e-04 -5.80e-04 -8.00e-05]
 [ 8.40e-04 -1.29e-03 -3.50e-04 -2.80e-04  8.40e-04 -6.10e-04]
 [-3.30e-04 -4.10e-04  5.90e-04 -3.60e-04 -3.30e-04 -2.70e-04]
 [ 2.10e-04 -2.60e-04 -3.60e-04  1.90e-04  2.10e-04 -1.30e-04]
 [-5.80e-04  1.02e-03  2.60e-04  2.60e-04 -5.80e-04 -8.00e-05]
 [ 3.40e-04 -6.80e-04  3.80e-04 -1.20e-03  3.40e-04 -1.40e-04]]


V matrix is calculated, but not in the calculation of this attenton score matrix yet.

at this stage:
$$\frac{QK^T}{\sqrt{d_k}}$$


---

## Step 3: Causal masking

In [6]:
lower_triangle_array_mask = np.tril(np.ones_like(attention_scores))
# array([[1., 0., 0., 0., 0., 0.],
#        [1., 1., 0., 0., 0., 0.],
#        [1., 1., 1., 0., 0., 0.],
#        [1., 1., 1., 1., 0., 0.],
#        [1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1.]])

attention_scores[lower_triangle_array_mask == 0] = - np.inf

np.round(attention_scores, 5)

array([[-0.00058,     -inf,     -inf,     -inf,     -inf,     -inf],
       [ 0.00084, -0.00129,     -inf,     -inf,     -inf,     -inf],
       [-0.00033, -0.00041,  0.00059,     -inf,     -inf,     -inf],
       [ 0.00021, -0.00026, -0.00036,  0.00019,     -inf,     -inf],
       [-0.00058,  0.00102,  0.00026,  0.00026, -0.00058,     -inf],
       [ 0.00034, -0.00068,  0.00038, -0.0012 ,  0.00034, -0.00014]])

- causal masked applied to the attention scores before softmax
- all tokens can only attend to itself and tokens before

---

## Step 4: Softmax

In [7]:
attention_weights = softmax(attention_scores, axis=-1)

np.round(attention_weights, 5)

array([[1.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.50053, 0.49947, 0.     , 0.     , 0.     , 0.     ],
       [0.33324, 0.33321, 0.33355, 0.     , 0.     , 0.     ],
       [0.25007, 0.24995, 0.24992, 0.25006, 0.     , 0.     ],
       [0.19987, 0.20019, 0.20004, 0.20004, 0.19987, 0.     ],
       [0.16675, 0.16658, 0.16676, 0.16649, 0.16675, 0.16667]])

$$\text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)$$

---

## Step 5: Full single-head attention forward pass

$$Attention(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$

In [17]:
scaled_dot_product_attention = attention_weights @ V
# (6, 6) @ (6, 8) -> (6, 8)
# back to original shape: 6 words, 8 dimensions

np.round(scaled_dot_product_attention, 5)

array([[-1.729e-02, -2.582e-02, -9.390e-03, -1.452e-02,  1.186e-02,
        -2.819e-02,  5.610e-03, -3.521e-02],
       [-4.530e-03, -4.313e-02, -4.980e-03, -5.970e-03, -1.688e-02,
        -7.260e-03, -7.000e-05, -1.092e-02],
       [ 9.300e-04, -2.637e-02,  1.610e-03,  9.480e-03, -7.160e-03,
        -1.174e-02,  5.350e-03, -6.210e-03],
       [-6.000e-05, -1.983e-02,  1.300e-04,  2.010e-03, -8.910e-03,
         1.890e-03, -2.800e-04, -7.090e-03],
       [-3.500e-03, -2.103e-02, -1.770e-03, -1.290e-03, -4.770e-03,
        -4.120e-03,  9.000e-04, -1.270e-02],
       [-3.690e-03, -2.806e-02, -1.090e-03, -1.061e-02, -1.337e-02,
        -2.440e-03,  1.360e-03, -6.630e-03]])

---

In [9]:
attention_scores @ V

array([[-1.72934977e-02, -2.58187560e-02, -9.39399795e-03,
        -1.45207865e-02,  1.18620361e-02, -2.81923403e-02,
         5.61414543e-03, -3.52064448e-02],
       [-4.53197783e-03, -4.31294357e-02, -4.97718144e-03,
        -5.96820718e-03, -1.68848789e-02, -7.26476627e-03,
        -6.86794396e-05, -1.09232257e-02],
       [ 9.29064507e-04, -2.63679703e-02,  1.61438553e-03,
         9.47754037e-03, -7.16067398e-03, -1.17399121e-02,
         5.35197985e-03, -6.21340067e-03],
       [-6.22027102e-05, -1.98320665e-02,  1.29012826e-04,
         2.00719548e-03, -8.91084569e-03,  1.88985540e-03,
        -2.82318771e-04, -7.09203017e-03],
       [-3.49995195e-03, -2.10344878e-02, -1.77127193e-03,
        -1.28904644e-03, -4.76908379e-03, -4.11719216e-03,
         8.95700110e-04, -1.27003585e-02],
       [-3.68507817e-03, -2.80622531e-02, -1.08687664e-03,
        -1.06117561e-02, -1.33728290e-02, -2.43873410e-03,
         1.35569847e-03, -6.62661237e-03]])

## Step 6: Rewrite in PyTorch and use a real embedding model

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Set random seed for reproducibility
torch.manual_seed(42)

print("PyTorch imported successfully.")

PyTorch imported successfully.


### Define PyTorch Embedding and Attention Parameters

In [ ]:
# Vocab and dimensions
english_words = ["the", "cat", "sat", "on", "the", "mat"]
unique_words = sorted(list(set(english_words)))
vocab_size = len(unique_words)
word_to_idx = {word: i for i, word in enumerate(unique_words)}

d_model = 8  # Dimension of embedding and attention
d_k = 8      # Dimension of queries, keys, values

# Create an embedding layer
embedding_layer = nn.Embedding(vocab_size, d_model)

# Convert words to indices
indexed_words = torch.tensor([word_to_idx[w] for w in english_words], dtype=torch.long)



# Get embeddings
X_torch = embedding_layer(indexed_words)

print("Vocabulary:", unique_words)
print("Indexed words:", indexed_words)
print("X_torch shape (embeddings):", X_torch.shape)

### PyTorch Attention Mechanism (Single Head)

In [ ]:
# Initialize linear layers for Q, K, V projections
W_q_torch = nn.Linear(d_model, d_k, bias=False)
W_k_torch = nn.Linear(d_model, d_k, bias=False)
W_v_torch = nn.Linear(d_model, d_k, bias=False)

# Project embeddings into Q, K, V spaces
Q_torch = W_q_torch(X_torch)
K_torch = W_k_torch(X_torch)
V_torch = W_v_torch(X_torch)

print("Q_torch shape:", Q_torch.shape)
print("K_torch shape:", K_torch.shape)
print("V_torch shape:", V_torch.shape)

In [ ]:
# Calculate attention scores: QK^T / sqrt(d_k)
attention_scores_torch = torch.matmul(Q_torch, K_torch.transpose(-2, -1)) / (d_k**0.5)

print("Attention Scores (PyTorch) shape:", attention_scores_torch.shape)
print("Attention Scores (PyTorch) (rounded):")
print(torch.round(attention_scores_torch, decimals=5))

### Causal Masking in PyTorch

In [ ]:
# Create causal mask (lower triangular matrix)
seq_len = X_torch.shape[0]
causal_mask = torch.tril(torch.ones(seq_len, seq_len)).bool()

# Apply mask: set upper triangle to -inf
attention_scores_masked_torch = attention_scores_torch.masked_fill(causal_mask == 0, float('-inf'))

print("Causal Mask:")
print(causal_mask)
print("Masked Attention Scores (PyTorch) (rounded):")
print(torch.round(attention_scores_masked_torch, decimals=5))

### Softmax in PyTorch

In [ ]:
# Apply softmax to get attention weights
attention_weights_torch = F.softmax(attention_scores_masked_torch, dim=-1)

print("Attention Weights (PyTorch) (rounded):")
print(torch.round(attention_weights_torch, decimals=5))

### Full Single-Head Attention Forward Pass in PyTorch

In [ ]:
# Calculate final output: Attention_weights @ V
scaled_dot_product_attention_torch = torch.matmul(attention_weights_torch, V_torch)

print("Scaled Dot-Product Attention Output (PyTorch) shape:", scaled_dot_product_attention_torch.shape)
print("Scaled Dot-Product Attention Output (PyTorch) (rounded):")
print(torch.round(scaled_dot_product_attention_torch, decimals=5))