<a href="https://colab.research.google.com/github/safakatakancelik/portfolio-public/blob/main/notebooks/building_attention_from_scratch/attention_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Implementing Attention

1. Raw attention with word embeddings, no Q/K/V
2. Add Q, K, V matrices
3. Causal masking
4. Softmax
5. Full single-head attention forward pass


6. Rewrite in PyTorch and use a real embedding model
7. Multi-head attention
7. Inspect attention matrices on ambiguous sentences
8. Rewrite as PyTorch nn.Module inside a transformer block (attention → residual → LayerNorm → FFN)

### Learning Goals
- understand raw attention vs learned Q/K/V projections
- see why √d_k scaling prevents softmax saturation
- understand causal masking for autoregressive generation
- read attention maps to see what the model "looks at"
- bridge from numpy prototype to production-style PyTorch code


$$Attention(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$


In [1]:
!pip install torch
!pip install torchtext
!pip install transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 33.4 MB/s eta 0:00:00


In [2]:
import numpy as np
from scipy.special import softmax

### Step 1: Tokenization of an example input vector X

In [16]:
np.random.seed(42)
d_model = 8
d_k = 8

# building the vocabulary with random vectors
english_words = ["the", "cat", "sat", "on", "the", "mat"]


unique_words = dict.fromkeys(english_words)
vocab = {w: np.random.randn(d_model) for w in unique_words}

X = np.array([vocab[w] for w in english_words])  # (6, 8)


print("Tokens:", english_words)
print(np.round(X, 2))

Tokens: ['the', 'cat', 'sat', 'on', 'the', 'mat']
[[ 0.5  -0.14  0.65  1.52 -0.23 -0.23  1.58  0.77]
 [-0.47  0.54 -0.46 -0.47  0.24 -1.91 -1.72 -0.56]
 [-1.01  0.31 -0.91 -1.41  1.47 -0.23  0.07 -1.42]
 [-0.54  0.11 -1.15  0.38 -0.6  -0.29 -0.6   1.85]
 [ 0.5  -0.14  0.65  1.52 -0.23 -0.23  1.58  0.77]
 [-0.01 -1.06  0.82 -1.22  0.21 -1.96 -1.33  0.2 ]]


---


## Step 2: Project Embeddings into Q, K, V spaces

In [17]:
# initialize projection matrices to train
W_q = np.random.randn(d_model, d_k) * 0.01
W_k = np.random.randn(d_model, d_k) * 0.01
W_v = np.random.randn(d_model, d_k) * 0.01


# project embeddings into Q, K, V spaces
Q = X @ W_q
K = X @ W_k
V = X @ W_v

In [23]:
## Attention scores
attention_scores = Q @ K.T / np.sqrt(d_k)  # (6, 6)

print("Tokens:", english_words)
print("\nScores shape:", attention_scores.shape)
print(np.round(attention_scores, 5))

Tokens: ['the', 'cat', 'sat', 'on', 'the', 'mat']

Scores shape: (6, 6)
[[-5.80e-04  1.02e-03  2.60e-04  2.60e-04 -5.80e-04 -8.00e-05]
 [ 8.40e-04 -1.29e-03 -3.50e-04 -2.80e-04  8.40e-04 -6.10e-04]
 [-3.30e-04 -4.10e-04  5.90e-04 -3.60e-04 -3.30e-04 -2.70e-04]
 [ 2.10e-04 -2.60e-04 -3.60e-04  1.90e-04  2.10e-04 -1.30e-04]
 [-5.80e-04  1.02e-03  2.60e-04  2.60e-04 -5.80e-04 -8.00e-05]
 [ 3.40e-04 -6.80e-04  3.80e-04 -1.20e-03  3.40e-04 -1.40e-04]]


$$attention \ scores = \frac{QK^T}{\sqrt{d_k}}$$


---

## Step 3: Causal masking

In [19]:
lower_triangle_array_mask = np.tril(np.ones_like(attention_scores))
# array([[1., 0., 0., 0., 0., 0.],
#        [1., 1., 0., 0., 0., 0.],
#        [1., 1., 1., 0., 0., 0.],
#        [1., 1., 1., 1., 0., 0.],
#        [1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1.]])

attention_scores[lower_triangle_array_mask == 0] = - np.inf

np.round(attention_scores, 5)

array([[-0.00058,     -inf,     -inf,     -inf,     -inf,     -inf],
       [ 0.00084, -0.00129,     -inf,     -inf,     -inf,     -inf],
       [-0.00033, -0.00041,  0.00059,     -inf,     -inf,     -inf],
       [ 0.00021, -0.00026, -0.00036,  0.00019,     -inf,     -inf],
       [-0.00058,  0.00102,  0.00026,  0.00026, -0.00058,     -inf],
       [ 0.00034, -0.00068,  0.00038, -0.0012 ,  0.00034, -0.00014]])

- causal mask applied to the attention scores before softmax
- all tokens can only attend to itself and tokens before

---

## Step 4: Softmax

In [20]:
attention_weights = softmax(attention_scores, axis=-1)

np.round(attention_weights, 5)

array([[1.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.50053, 0.49947, 0.     , 0.     , 0.     , 0.     ],
       [0.33324, 0.33321, 0.33355, 0.     , 0.     , 0.     ],
       [0.25007, 0.24995, 0.24992, 0.25006, 0.     , 0.     ],
       [0.19987, 0.20019, 0.20004, 0.20004, 0.19987, 0.     ],
       [0.16675, 0.16658, 0.16676, 0.16649, 0.16675, 0.16667]])

$$\text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)$$

---

## Step 5: Full single-head attention forward pass

$$Attention(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V$$

In [ ]:
scaled_dot_product_attention = attention_weights @ V
# (6, 6) @ (6, 8) -> (6, 8)
# back to original shape: 6 words, 8 dimensions

np.round(scaled_dot_product_attention, 5)
# 5th row, index 4, is the numerical representation to decode the 6th word "mat"

array([[-1.729e-02, -2.582e-02, -9.390e-03, -1.452e-02,  1.186e-02,
        -2.819e-02,  5.610e-03, -3.521e-02],
       [-4.530e-03, -4.313e-02, -4.980e-03, -5.970e-03, -1.688e-02,
        -7.260e-03, -7.000e-05, -1.092e-02],
       [ 9.300e-04, -2.637e-02,  1.610e-03,  9.480e-03, -7.160e-03,
        -1.174e-02,  5.350e-03, -6.210e-03],
       [-6.000e-05, -1.983e-02,  1.300e-04,  2.010e-03, -8.910e-03,
         1.890e-03, -2.800e-04, -7.090e-03],
       [-3.500e-03, -2.103e-02, -1.770e-03, -1.290e-03, -4.770e-03,
        -4.120e-03,  9.000e-04, -1.270e-02],
       [-3.690e-03, -2.806e-02, -1.090e-03, -1.061e-02, -1.337e-02,
        -2.440e-03,  1.360e-03, -6.630e-03]])

---

## Step 6: Rewrite in PyTorch and use a real embedding model

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel

# 1. Load BERT-Tiny (Only 17MB!)
tokenizer = AutoTokenizer.from_pretrained("prajjwal1/bert-tiny")
tiny_model = AutoModel.from_pretrained("prajjwal1/bert-tiny")

# 2. Extract strictly the Word Embedding layer
# (BERT names its embedding layer differently than GPT-2)
real_embedding_layer = tiny_model.embeddings.word_embeddings
D_MODEL = real_embedding_layer.embedding_dim

print(f"Real Vocab Size: {real_embedding_layer.num_embeddings} words")
print(f"Real Dimension (d_model): {D_MODEL} features per word")

# 3. Tokenize your exact sentence
sentence = "the cat sat on the mat"
tokens = tokenizer(sentence, return_tensors="pt")
input_ids = tokens["input_ids"]

print(f"\nReal Tokens: {tokenizer.convert_ids_to_tokens(input_ids[0])}")
print(f"Real Token IDs: {input_ids}")

# 4. Pass the IDs through the real pre-trained embeddings
X = real_embedding_layer(input_ids)
print(f"\nShape of our Input X: {X.shape} -> (Batch, Seq_Len, d_model)")

Loading weights:   0%|          | 0/39 [00:00<?, ?it/s]

BertModel LOAD REPORT from: prajjwal1/bert-tiny
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.decoder.bias               | UNEXPECTED |  | 
bert.embeddings.position_ids               | UNEXPECTED |  | 
cls.predictions.decoder.weight             | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Real Vocab Size: 30522 words
Real Dimension (d_model): 128 features per word

Real Tokens: ['[CLS]', 'the', 'cat', 'sat', 'on', 'the', 'mat', '[SEP]']
Real Token IDs: tensor([[  101,  1996,  4937,  2938,  2006,  1996, 13523,   102]])

Shape of our Input X: torch.Size([1, 8, 128]) -> (Batch, Seq_Len, d_model)


In [21]:
class PyTorchSelfAttention(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        self.q_proj = nn.Linear(d_model, d_model, bias=False)
        self.k_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj = nn.Linear(d_model, d_model, bias=False)

    def forward(self, x):
        # 1. Project the real embeddings into Q, K, V
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        # 2. FlashAttention handles the scaling, causal masking, Softmax, and V multiplication!
        # (Requires PyTorch 2.0+)
        output = F.scaled_dot_product_attention(
            query=q,
            key=k,
            value=v,
            is_causal=True  # Automatically applies the lower-triangle mask
        )

        return output

attention_layer = PyTorchSelfAttention(d_model=D_MODEL)

final_output = attention_layer(X)

print(f"Final Attention Output Shape: {final_output.shape}")
print(f"Row 5 (Used to predict the 6th word):\n{final_output[0, 4, :10]}... (showing first 10 dims)")


Final Attention Output Shape: torch.Size([1, 8, 128])
Row 5 (Used to predict the 6th word):
tensor([ 0.0053,  0.0095, -0.0045,  0.0225, -0.0138,  0.0101, -0.0015, -0.0105,
         0.0029, -0.0133], grad_fn=<SliceBackward0>)... (showing first 10 dims)


In [25]:
#### DECODE
# 1. We need an LM Head (Unembedding Matrix)
# In a real model, this is heavily trained. Here, we'll just initialize a random one.
# It maps from our features (128) -> our entire dictionary (30,522)
lm_head = nn.Linear(D_MODEL, real_embedding_layer.num_embeddings)

# Let's say we want to predict the word that comes AFTER "mat"
# In BERT-Tiny, "mat" is at index 6 (because of the [CLS] token at the start)
vector_to_decode = final_output[0, 6, :]  # Shape: (128)

# 2. Project the vector into Vocabulary Space
# This gives us 30,522 raw scores (logits)
logits = lm_head(vector_to_decode)  # Shape: (30522)

# 3. Find the index of the highest score!
# torch.argmax looks at all 30,522 scores and returns the ID of the biggest one
predicted_token_id = torch.argmax(logits)

# 4. Use the tokenizer to translate that ID back into English
predicted_word = tokenizer.decode(predicted_token_id)

print(f"Predicted Token ID: {predicted_token_id}")
print(f"The model predicts the next word is: '{predicted_word}'")


Predicted Token ID: 26135
The model predicts the next word is: 'ferreira'
